### ISSUE TITLE
List of indexed and non-indexed servers

### ISSUE THREAD

**Issue by hauschke** [LeakIX/mastosearch#1]
A list of all servers with an indicator if it is indexed or not would be really helpful to assess the scope of the FedSearch. It is already incredibly useful, but this would make it much easer to judge search results.

**Comment by gboddin** [comment]
There's no excluded servers in this code.

Instead we use the user's choice by checking if he allowed search engine to grab the content or not.

In mastodon >= 4.0.0 this is achieved by using the `noindex` field from the local stream.
In mastodon < 4.0.0 a request is made to the user profile page to check for a robot `meta` tag that would contain `noindex`

The drawback with mastodon < 4.0.0 is that it might create a huge load on mastodon servers.
We have added a rate limiter a safe guard but the side effect will be memory leaking and or deconnections when users are posting at rate higher than the limit we've set.
